# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xsenia', '0004_structure_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='type',
            new_name='kind',
        ),
    ]
