version: '2'
volumes:
  data: {}
services:
  web:
    build: ./web
    volumes:
      - './web/site.conf:/etc/nginx/conf.d/site.conf:ro'
      - './static:/code/static:ro'
    ports: ['0.0.0.0:8080:8080']
    depends_on: [app, ui]
    restart: on-failure
  ui:
    build: ./ui
    command: nodemon -x 'gulp serve' -w /code/gulpfile.js
    volumes: ['./ui:/code:rw']
    ports:
    - 0.0.0.0:3001:3001
    - 0.0.0.0:8082:8080
    depends_on: [app]
    restart: always
  app:
    build: .
    volumes: ['.:/code:rw']
    ports: ['0.0.0.0:8081:8080']
    depends_on: [db]
    env_file: config.env
    restart: always
  db:
    container_name: db
    image: postgres:9.5
    restart: on-failure
    env_file: config.env
    volumes: ['data:/var/lib/postgresql/data/hom:rw']
  mongo:
    image: mongo
    restart: on-failure
