swagger: '2.0'
info:
  title: Xenia
  description: API per Xenia
  version: "1.0"
host: localhost:9000
schemes:
  - http
basePath: /xenia
produces:
  - application/json


####################################
########### DEFINITIONS ############

definitions:

  evacueeCategory:
    type: string
    enum: &evacueeCategory
      - pregnant
      - handicapped
      - child
      - teen
      - adult
      - elder


  address:
    type: object
    properties:
      id:
        type: string
      text:
        type: string
      phone:
        type: string
      city:
        type: string
      state:
        type: string
      zip:
        type: string
      country:
        type: string
      latitude:
        type: number
      longitude:
        type: number


  assignment:
    type: object
    properties:
      id:
        type: string
      timestamp:
        type: number
      evacuee_id:
        type: string


  structure:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      address:
        $ref: "#/definitions/address"
      description:
        type: string
      total_seats:
        type: number
      available_seats:
        type: number
      available: # tenerlo?
        type: boolean
      active:
        type: boolean
      evacuees:
        type: array
        items:
          $ref: "#/definitions/evacuee"


  volunteer:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      surname:
        type: string
      fiscal_code:
        type: string
      address:
        $ref: "#/definitions/address"
      email:
        type: string
      password:
        type: string
      structures:
        type: array
        items:
          $ref: "#/definitions/structure"
      note:
        type: string


  evacuee:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      surname:
        type: string
      fiscal_code:
        type: string
      address:
        $ref: "#/definitions/address"
      email:
        type: string
      password:
        type: string
      category:
        $ref: "#/definitions/evacueeCategory"
      assigned:
        type: boolean
      group:
        type: array
        items:
          $ref: "#/definitions/simpleEvacuee"


  simpleEvacuee:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      surname:
        type: string
      fiscal_code:
        type: string
      category:
        $ref: "#/definitions/evacueeCategory"


  administrator:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      surname:
        type: string
      email:
        type: string
      password:
        type: string


####################################
############## PATHS ###############


paths:
  '/volunteers/':
    get:
      produces:
        - application/json
      responses:
        200:
          description: lista dei volontari
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '#/definitions/volunteer'
    post:
      parameters:
        - name: volunteer
          in: body
          description: creazione volontario
          required: true
          schema:
            $ref: '#/definitions/volunteer'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: tutto ok
  '/volunteers/{volunteerId}':
    get:
      produces:
        - application/json
      parameters:
      - name: volunteerId
        in: path
        required: true
        type: string
      responses:
        200:
          description: singolo volontario
          schema:
            type: object
            properties:
              volunteer:
                $ref: '#/definitions/volunteer'
  '/evacuees/':
    get:
      produces:
        - application/json
      responses:
        200:
          description: lista sfollati
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '#/definitions/evacuee'
    post:
      parameters:
        - name: evacuee
          in: body
          description: creazione sfollato
          required: true
          schema:
            $ref: '#/definitions/evacuee'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: tutto ok
  '/evacuees/{evacueeId}':
    get:
      produces:
        - application/json
      parameters:
      - name: evacueeId
        in: path
        required: true
        type: string
      responses:
        200:
          description: singolo sfollato
          schema:
            type: object
            properties:
              volunteer:
                $ref: '#/definitions/evacuee'
  '/structures/':
    get:
      produces:
        - application/json
      responses:
        200:
          description: lista strutture
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '#/definitions/structure'
    post:
      parameters:
        - name: structure
          in: body
          description: creazione struttura
          required: true
          schema:
            $ref: '#/definitions/structure'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: tutto ok
  '/structures/{structureId}':
    get:
      produces:
        - application/json
      parameters:
      - name: structureId
        in: path
        required: true
        type: string
      responses:
        200:
          description: singola struttura
          schema:
            type: object
            properties:
              volunteer:
                $ref: '#/definitions/structure'